var startGame = false;
var background;
var player;
var enemies;
var NUM_STARS = 50;
var hq;
var mountains;
var scoreboard;
var cursors;
var fireKey;
var gameOver = false;
var playerStartY = 406;
var playerStartX = 210;
var houses;
var border;
var stars;